In [1]:
import pandas as pd

In [2]:
fert = pd.read_csv("../data/fert.csv").set_index("Country Code")
fert

,Country Name,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,Unnamed: 61
Country Code,,,,,,,,,,,,,,,,,,,,,
ABW,Aruba,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,4.820000,4.655000,4.471000,4.271000,4.059000,3.842000,3.625000,...,1.728000,1.716000,1.704000,1.692000,1.680000,1.669000,1.657000,1.647000,NaN,NaN
AFG,Afghanistan,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.450000,7.450000,7.450000,7.450000,7.450000,7.450000,7.450000,...,6.218000,5.985000,5.746000,5.506000,5.272000,5.050000,4.843000,4.653000,NaN,NaN
AGO,Angola,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.379000,7.388000,7.396000,7.402000,7.406000,7.408000,7.406000,...,6.559000,6.492000,6.416000,6.335000,6.251000,6.165000,6.080000,5.996000,NaN,NaN
ALB,Albania,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.489000,6.401000,6.282000,6.133000,5.960000,5.773000,5.581000,...,1.625000,1.636000,1.663000,1.699000,1.735000,1.765000,1.784000,1.793000,NaN,NaN
AND,Andorra,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.250000,1.190000,1.270000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ARB,Arab World,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.920302,6.941665,6.959471,6.971402,6.975507,6.970647,6.954848,...,3.448331,3.448205,3.449015,3.446814,3.437146,3.417848,3.387747,3.347607,NaN,NaN
ARE,United Arab Emirates,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.928000,6.910000,6.893000,6.877000,6.861000,6.841000,6.816000,...,1.948000,1.903000,1.868000,1.841000,1.820000,1.801000,1.784000,1.767000,NaN,NaN
ARG,Argentina,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,3.109000,3.100000,3.089000,3.078000,3.068000,3.058000,3.051000,...,2.396000,2.382000,2.370000,2.358000,2.347000,2.335000,2.322000,2.308000,NaN,NaN
ARM,Armenia,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,4.550000,4.512000,4.435000,4.317000,4.161000,3.979000,3.788000,...,1.707000,1.680000,1.648000,1.613000,1.581000,1.553000,1.531000,1.517000,NaN,NaN
ASM,American Samoa,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ATG,Antigua and Barbuda,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,4.425000,4.386000,4.344000,4.299000,4.250000,4.193000,4.125000,...,2.164000,2.146000,2.130000,2.115000,2.102000,2.088000,2.075000,2.063000,NaN,NaN
AUS,Australia,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,3.453000,3.540000,3.442000,3.332000,3.146000,2.977000,2.881000,...,1.984000,1.971000,1.928000,1.927000,1.921000,1.859000,1.833000,1.833000,NaN,NaN
AUT,Austria,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,2.690000,2.780000,2.800000,2.820000,2.790000,2.700000,2.660000,...,1.420000,1.390000,1.440000,1.430000,1.440000,1.440000,1.470000,1.470000,NaN,NaN
AZE,Azerbaijan,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,5.571000,5.596000,5.591000,5.549000,5.468000,5.352000,5.210000,...,1.900000,1.820000,1.920000,1.960000,2.000000,1.980000,1.970000,1.970000,NaN,NaN
BDI,Burundi,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.953000,6.998000,7.045000,7.092000,7.138000,7.179000,7.216000,...,6.480000,6.391000,6.302000,6.212000,6.123000,6.035000,5.948000,5.863000,NaN,NaN
BEL,Belgium,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,2.540000,2.630000,2.590000,2.680000,2.710000,2.610000,2.520000,...,1.850000,1.840000,1.860000,1.810000,1.790000,1.750000,1.740000,1.740000,NaN,NaN
BEN,Benin,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.282000,6.339000,6.394000,6.447000,6.497000,6.544000,6.588000,...,5.272000,5.182000,5.094000,5.009000,4.927000,4.846000,4.766000,4.688000,NaN,NaN
BFA,Burkina Faso,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.291000,6.316000,6.344000,6.377000,6.414000,6.454000,6.493000,...,6.036000,5.953000,5.867000,5.780000,5.693000,5.607000,5.521000,5.437000,NaN,NaN
BGD,Bangladesh,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.725000,6.761000,6.794000,6.825000,6.853000,6.878000,6.901000,...,2.449000,2.387000,2.332000,2.286000,2.245000,2.209000,2.175000,2.144000,NaN,NaN
BGR,Bulgaria,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,2.310000,2.290000,2.240000,2.210000,2.190000,2.090000,2.030000,...,1.560000,1.660000,1.570000,1.510000,1.500000,1.480000,1.530000,1.530000,NaN,NaN
BHR,Bahrain,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.090000,7.132000,7.168000,7.190000,7.192000,7.165000,7.101000,...,2.229000,2.179000,2.142000,2.115000,2.095000,2.075000,2.056000,2.035000,NaN,NaN
BHS,"Bahamas, The","Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,4.495000,4.496000,4.450000,4.356000,4.220000,4.057000,3.893000,...,1.891000,1.901000,1.904000,1.900000,1.893000,1.883000,1.872000,1.861000,NaN,NaN
BIH,Bosnia and Herzegovina,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,3.770000,3.720000,3.665000,3.599000,3.517000,3.422000,3.318000,...,1.270000,1.283000,1.288000,1.286000,1.280000,1.272000,1.263000,1.253000,NaN,NaN
BLR,Belarus,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,2.670000,2.590000,2.500000,2.400000,2.310000,2.270000,2.290000,...,1.488000,1.509000,1.494000,1.515000,1.620000,1.668000,1.696000,1.724000,NaN,NaN
BLZ,Belize,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.500000,6.480000,6.460000,6.440000,6.420000,6.400000,6.379000,...,2.821000,2.762000,2.714000,2.676000,2.643000,2.611000,2.579000,2.546000,NaN,NaN
BMU,Bermuda,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.770000,1.760000,1.760000,1.590000,1.590000,1.630000,1.630000,1.620000,NaN,NaN
BOL,Bolivia,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.700000,6.668000,6.633000,6.597000,6.559000,6.519000,6.477000,...,3.348000,3.271000,3.200000,3.133000,3.073000,3.017000,2.968000,2.923000,NaN,NaN
BRA,Brazil,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.210000,6.190000,6.143000,6.063000,5.953000,5.815000,5.658000,...,1.898000,1.863000,1.838000,1.823000,1.812000,1.801000,1.790000,1.778000,NaN,NaN
BRB,Barbados,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,4.333000,4.313000,4.269000,4.196000,4.094000,3.963000,3.807000,...,1.772000,1.777000,1.781000,1.785000,1.788000,1.791000,1.794000,1.796000,NaN,NaN
BRN,Brunei Darussalam,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.487000,6.487000,6.448000,6.360000,6.227000,6.068000,5.918000,...,1.977000,1.968000,1.953000,1.934000,1.913000,1.893000,1.874000,1.856000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TLA,Latin America & the Caribbean (IDA & IBRD coun...,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.046537,6.037526,6.014624,5.974721,5.919214,5.848223,5.764277,...,2.276721,2.243754,2.215453,2.191405,2.169609,2.148535,2.127681,2.106664,NaN,NaN
TLS,Timor-Leste,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.373000,6.376000,6.375000,6.367000,6.347000,6.314000,6.268000,...,6.477000,6.358000,6.235000,6.109000,5.983000,5.858000,5.735000,5.615000,NaN,NaN
TMN,Middle East & North Africa (IDA & IBRD countries),"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.916244,6.933149,6.945009,6.949615,6.944734,6.928759,6.899112,...,2.839880,2.857843,2.876332,2.889593,2.893882,2.887182,2.868434,2.838520,NaN,NaN
TON,Tonga,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.363000,7.346000,7.302000,7.226000,7.117000,6.974000,6.795000,...,4.012000,3.963000,3.913000,3.864000,3.815000,3.768000,3.722000,3.678000,NaN,NaN
TSA,South Asia (IDA & IBRD),"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.045700,6.045306,6.040937,6.031951,6.016822,5.994972,5.967227,...,2.888908,2.822908,2.759512,2.700985,2.647534,2.600646,2.559252,2.522665,NaN,NaN
TSS,Sub-Saharan Africa (IDA & IBRD countries),"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.622001,6.633827,6.644035,6.652707,6.659583,6.666003,6.673228,...,5.364677,5.304206,5.242469,5.178494,5.112690,5.044903,4.975894,4.905575,NaN,NaN
TTO,Trinidad and Tobago,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,5.264000,5.177000,5.047000,4.873000,4.664000,4.433000,4.200000,...,1.799000,1.804000,1.806000,1.804000,1.798000,1.789000,1.778000,1.766000,NaN,NaN
TUN,Tunisia,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.942000,6.970000,6.993000,7.009000,7.015000,7.008000,6.984000,...,2.042000,2.070000,2.098000,2.122000,2.138000,2.146000,2.144000,2.132000,NaN,NaN
TUR,Turkey,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.303000,6.241000,6.175000,6.104000,6.029000,5.951000,5.874000,...,2.170000,2.151000,2.134000,2.118000,2.103000,2.087000,2.070000,2.052000,NaN,NaN
TUV,Tuvalu,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TZA,Tanzania,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.806000,6.806000,6.804000,6.803000,6.801000,6.798000,6.795000,...,5.542000,5.489000,5.427000,5.359000,5.287000,5.215000,5.145000,5.078000,NaN,NaN
UGA,Uganda,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.999000,7.019000,7.040000,7.060000,7.078000,7.094000,7.106000,...,6.337000,6.247000,6.154000,6.059000,5.964000,5.869000,5.775000,5.682000,NaN,NaN
UKR,Ukraine,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,2.240000,2.170000,2.140000,2.060000,1.960000,1.990000,2.020000,...,1.458000,1.473000,1.443000,1.459000,1.531000,1.506000,1.498000,1.506000,NaN,NaN
UMC,Upper middle income,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,5.317314,5.371649,5.461534,5.527377,5.571433,5.590075,5.571052,...,1.785243,1.785116,1.785414,1.785621,1.793046,1.793540,1.797601,1.796789,NaN,NaN
URY,Uruguay,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,2.880000,2.886000,2.884000,2.874000,2.858000,2.841000,2.830000,...,2.110000,2.094000,2.078000,2.063000,2.048000,2.033000,2.020000,2.007000,NaN,NaN
USA,United States,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,3.654000,3.620000,3.461000,3.319000,3.190000,2.913000,2.721000,...,2.072000,2.002000,1.931000,1.894500,1.880500,1.857500,1.862500,1.843000,NaN,NaN
UZB,Uzbekistan,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.707000,6.755000,6.783000,6.790000,6.777000,6.748000,6.707000,...,2.637000,2.530000,2.342000,2.236000,2.193000,2.350000,2.457000,2.491000,NaN,NaN
VCT,St. Vincent and the Grenadines,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.224000,7.155000,7.074000,6.981000,6.876000,6.760000,6.632000,...,2.112000,2.092000,2.070000,2.046000,2.021000,1.997000,1.974000,1.952000,NaN,NaN
VEN,"Venezuela, RB","Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.616000,6.637000,6.628000,6.581000,6.495000,6.368000,6.203000,...,2.531000,2.501000,2.472000,2.444000,2.417000,2.391000,2.365000,2.340000,NaN,NaN
VGB,British Virgin Islands,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VIR,Virgin Islands (U.S.),"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,5.615000,5.651000,5.679000,5.696000,5.698000,5.679000,5.634000,...,1.910000,1.860000,1.810000,1.800000,1.780000,1.770000,1.750000,1.740000,NaN,NaN
VNM,Vietnam,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.348000,6.392000,6.425000,6.448000,6.464000,6.475000,6.485000,...,1.923000,1.935000,1.946000,1.953000,1.957000,1.960000,1.961000,1.960000,NaN,NaN
VUT,Vanuatu,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.197000,7.120000,7.033000,6.938000,6.836000,6.730000,6.626000,...,3.608000,3.549000,3.499000,3.456000,3.419000,3.383000,3.347000,3.310000,NaN,NaN
WLD,World,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,4.984260,5.007913,5.030031,5.050497,5.061055,5.044661,4.995178,...,2.534969,2.516938,2.502575,2.487415,2.479700,2.466110,2.460116,2.451201,NaN,NaN
WSM,Samoa,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.651000,7.645000,7.630000,7.604000,7.567000,7.519000,7.462000,...,4.426000,4.389000,4.338000,4.277000,4.212000,4.147000,4.086000,4.028000,NaN,NaN
XKX,Kosovo,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.380000,2.340000,2.290000,2.240000,2.190000,2.160000,2.130000,2.090000,NaN,NaN
YEM,"Yemen, Rep.","Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.380000,7.405000,7.437000,7.475000,7.519000,7.566000,7.611000,...,5.016000,4.856000,4.703000,4.556000,4.416000,4.284000,4.160000,4.043000,NaN,NaN
ZAF,South Africa,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.173000,6.144000,6.103000,6.049000,5.984000,5.911000,5.836000,...,2.538000,2.500000,2.467000,2.438000,2.412000,2.387000,2.363000,2.339000,NaN,NaN
ZMB,Zambia,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.018000,7.071000,7.127000,7.184000,7.240000,7.292000,7.338000,...,5.847000,5.772000,5.687000,5.599000,5.511000,5.429000,5.353000,5.284000,NaN,NaN
ZWE,Zimbabwe,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.158000,7.215000,7.267000,7.311000,7.347000,7.373000,7.391000,...,4.034000,4.044000,4.048000,4.039000,4.016000,3.977000,3.923000,3.856000,NaN,NaN

In [3]:
lfe = pd.read_csv("../data/life_expectancy.csv").set_index("Country Code")
lfe

,Country Name,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,Unnamed: 61
Country Code,,,,,,,,,,,,,,,,,,,,,
ABW,Aruba,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,65.569366,65.988024,66.365537,66.713976,67.044293,67.369756,67.699000,...,74.675732,74.818146,74.953537,75.081390,75.205756,75.328659,75.451098,75.573585,NaN,NaN
AFG,Afghanistan,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,32.328512,32.777439,33.219902,33.657878,34.092878,34.525390,34.957415,...,58.225024,58.603683,58.970829,59.327951,59.679610,60.028268,60.374463,60.717171,NaN,NaN
AGO,Angola,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,32.984829,33.386220,33.787585,34.188463,34.590341,34.992220,35.395098,...,49.847390,50.251024,50.654171,51.059317,51.464000,51.866171,52.266878,52.666098,NaN,NaN
ALB,Albania,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,62.254366,63.273463,64.162854,64.887098,65.438195,65.827390,66.089317,...,76.652073,76.840366,77.036951,77.240585,77.443976,77.640463,77.830463,78.014463,NaN,NaN
AND,Andorra,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ARB,Arab World,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,46.852780,47.432448,48.010502,48.591241,49.175538,49.758702,50.330956,...,69.361987,69.560038,69.749303,69.935670,70.125413,70.319844,70.517163,70.714065,NaN,NaN
ARE,United Arab Emirates,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,52.243220,53.286561,54.327000,55.363512,56.392585,57.405707,58.391854,...,76.307756,76.494780,76.675244,76.851195,77.024146,77.195634,77.368171,77.541244,NaN,NaN
ARG,Argentina,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,65.215537,65.338512,65.432610,65.509390,65.582415,65.668683,65.782244,...,75.166268,75.324561,75.484976,75.649049,75.816244,75.986098,76.158610,76.334220,NaN,NaN
ARM,Armenia,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,65.863463,66.284390,66.709854,67.137854,67.565415,67.991537,68.414732,...,73.945000,74.095829,74.226341,74.342829,74.452098,74.561366,74.675707,74.797122,NaN,NaN
ASM,American Samoa,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ATG,Antigua and Barbuda,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,61.782732,62.195415,62.598537,62.992585,63.378585,63.756073,64.125561,...,74.979171,75.147024,75.308780,75.466024,75.621805,75.778659,75.937634,76.100220,NaN,NaN
AUS,Australia,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,70.817073,70.973171,70.942439,70.911707,70.880976,70.850244,70.819512,...,81.395122,81.543902,81.695122,81.895122,82.046341,82.148780,82.300000,82.451220,NaN,NaN
AUT,Austria,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,68.585610,69.577317,69.309512,69.443659,69.921951,69.722195,70.045854,...,80.431707,80.331707,80.580488,80.982927,80.936585,81.136585,81.490244,81.843902,NaN,NaN
AZE,Azerbaijan,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,60.836244,61.239171,61.644585,62.052000,62.457415,62.861829,63.267268,...,70.063951,70.293683,70.451317,70.551805,70.623951,70.690585,70.763220,70.848780,NaN,NaN
BDI,Burundi,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,41.236049,41.545463,41.860390,42.177805,42.492220,42.790146,43.055073,...,53.891024,54.351220,54.829195,55.312024,55.789293,56.251610,56.692024,57.107049,NaN,NaN
BEL,Belgium,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,69.701951,70.520976,70.219512,70.051463,70.755122,70.625366,70.706341,...,79.680488,79.982927,80.182927,80.585366,80.385366,80.587805,81.287805,81.287805,NaN,NaN
BEN,Benin,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,37.278268,37.731195,38.189415,38.657341,39.136854,39.632732,40.148244,...,58.204512,58.491268,58.729707,58.932902,59.121976,59.312024,59.510585,59.720707,NaN,NaN
BFA,Burkina Faso,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,34.477902,34.938634,35.405878,35.879659,36.358951,36.837756,37.309049,...,55.902293,56.524976,57.051390,57.492049,57.879317,58.240634,58.588463,58.931293,NaN,NaN
BGD,Bangladesh,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,45.829317,46.457927,47.083976,47.692463,48.255439,48.689537,48.895415,...,69.277854,69.683780,70.080293,70.471951,70.860268,71.245244,71.625902,72.001195,NaN,NaN
BGR,Bulgaria,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,69.247561,70.195610,69.491951,70.309268,71.121220,71.293902,71.223415,...,72.963415,73.412195,73.512195,74.163415,74.314634,74.860976,74.465854,74.465854,NaN,NaN
BHR,Bahrain,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,52.089366,53.458512,54.818268,56.146585,57.425878,58.640073,59.783122,...,75.847512,75.987780,76.127561,76.267854,76.407634,76.545951,76.683268,76.819098,NaN,NaN
BHS,"Bahamas, The","Life expectancy at birth, total (years)",SP.DYN.LE00.IN,62.729049,63.072512,63.408024,63.737049,64.059098,64.374683,64.683780,...,74.247439,74.423902,74.592390,74.754415,74.914463,75.073537,75.233659,75.396829,NaN,NaN
BIH,Bosnia and Herzegovina,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,60.276220,60.941585,61.567976,62.162341,62.733683,63.292000,63.844854,...,75.511976,75.657366,75.807683,75.962927,76.120171,76.276927,76.433244,76.588585,NaN,NaN
BLR,Belarus,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,67.708098,68.212659,68.635829,68.992073,69.289927,69.537415,69.734610,...,70.456098,70.407317,70.404878,70.553659,71.965854,72.470732,72.970732,73.624390,NaN,NaN
BLZ,Belize,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,59.961366,60.512780,61.074341,61.646049,62.224829,62.806122,63.385341,...,69.594220,69.703073,69.782049,69.843683,69.905146,69.982049,70.077439,70.192366,NaN,NaN
BMU,Bermuda,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,NaN,NaN,NaN,NaN,NaN,68.897805,NaN,...,79.236585,79.388439,79.288537,81.152683,81.677805,80.572439,80.797317,81.012195,NaN,NaN
BOL,Bolivia,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,42.118317,42.433439,42.757049,43.089146,43.430220,43.779780,44.137805,...,65.273805,65.848000,66.407756,66.942561,67.445463,67.913439,68.344000,68.739610,NaN,NaN
BRA,Brazil,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,54.205463,54.718707,55.235659,55.751390,56.262951,56.767366,57.265683,...,72.695415,72.978024,73.264146,73.552341,73.839585,74.122439,74.401878,74.675878,NaN,NaN
BRB,Barbados,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,60.738049,61.215098,61.696171,62.182268,62.672878,63.161024,63.638634,...,74.519195,74.682488,74.845293,75.008146,75.171024,75.333951,75.496415,75.658439,NaN,NaN
BRN,Brunei Darussalam,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,62.500366,63.048951,63.575902,64.076195,64.548317,64.992293,65.412122,...,76.956756,77.268293,77.598268,77.932317,78.252585,78.546659,78.809585,79.040829,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TLA,Latin America & the Caribbean (IDA & IBRD coun...,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,55.619766,56.109489,56.579322,57.029450,57.462965,57.884675,58.301331,...,73.461234,73.684900,73.909557,74.136581,74.365043,74.594249,74.824819,75.055892,NaN,NaN
TLS,Timor-Leste,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,33.737122,34.237561,34.739049,35.241537,35.743488,36.282902,36.904780,...,66.457829,66.946683,67.308390,67.576732,67.800146,68.020902,68.259146,68.526415,NaN,NaN
TMN,Middle East & North Africa (IDA & IBRD countries),"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,46.656495,47.242920,47.826069,48.410245,48.997019,49.582825,50.159732,...,71.070463,71.277144,71.479537,71.680545,71.882935,72.085222,72.284353,72.476299,NaN,NaN
TON,Tonga,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,61.364537,61.732707,62.097293,62.458756,62.815146,63.167976,63.518317,...,71.883195,72.031756,72.182610,72.334732,72.488000,72.640341,72.792195,72.944049,NaN,NaN
TSA,South Asia (IDA & IBRD),"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,41.960597,42.600038,43.243690,43.886697,44.537386,45.180598,45.809556,...,65.925156,66.307643,66.689720,67.066432,67.431505,67.782021,68.116287,68.433245,NaN,NaN
TSS,Sub-Saharan Africa (IDA & IBRD countries),"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,40.155152,40.596924,41.029239,41.450557,41.861044,42.263354,42.660988,...,54.897254,55.623587,56.308740,56.940380,57.521404,58.053491,58.537123,58.974621,NaN,NaN
TTO,Trinidad and Tobago,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,62.657585,63.253756,63.760195,64.161390,64.455780,64.651756,64.770171,...,69.428927,69.610585,69.797561,69.980317,70.151390,70.305293,70.440561,70.557707,NaN,NaN
TUN,Tunisia,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,42.009756,42.645512,43.341683,44.100780,44.923854,45.814415,46.774951,...,74.577659,74.601707,74.611707,74.626220,74.662220,74.729756,74.835341,74.975976,NaN,NaN
TUR,Turkey,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,45.384415,46.104488,46.836707,47.574024,48.306317,49.023439,49.715732,...,73.500756,73.803220,74.090927,74.367341,74.636805,74.900707,75.163512,75.426220,NaN,NaN
TUV,Tuvalu,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TZA,Tanzania,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,43.653878,43.907293,44.162244,44.423707,44.697707,44.988732,45.296293,...,59.314707,60.509512,61.625610,62.632098,63.520902,64.291829,64.943902,65.487488,NaN,NaN
UGA,Uganda,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,43.983561,44.560024,45.147049,45.738122,46.321268,46.879488,47.394756,...,54.461976,55.182098,55.836659,56.463756,57.100195,57.767683,58.466415,59.179073,NaN,NaN
UKR,Ukraine,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,68.299537,68.763854,69.146098,69.457707,69.708220,69.905634,70.056537,...,68.251463,69.190000,70.265366,70.809268,70.944146,71.159512,71.186585,71.189512,NaN,NaN
UMC,Upper middle income,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,49.574848,50.092661,50.743098,51.581889,52.650624,53.890813,55.214694,...,73.227471,73.505590,73.726828,73.994262,74.224724,74.461595,74.669285,74.871426,NaN,NaN
URY,Uruguay,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,67.896390,68.112780,68.296634,68.440927,68.543146,68.606805,68.635927,...,76.101073,76.248585,76.394610,76.541195,76.688390,76.836195,76.986146,77.138220,NaN,NaN
USA,United States,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,69.770732,70.270732,70.119512,69.917073,70.165854,70.214634,70.212195,...,78.039024,78.390244,78.541463,78.641463,78.741463,78.741463,78.741463,78.741463,NaN,NaN
UZB,Uzbekistan,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,58.885537,59.297537,59.713024,60.130024,60.546537,60.957049,61.357585,...,67.634195,67.744561,67.861293,67.981415,68.101976,68.222000,68.339024,68.453073,NaN,NaN
VCT,St. Vincent and the Grenadines,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,57.723878,58.809683,59.839220,60.782390,61.621146,62.347463,62.969829,...,71.931732,72.150073,72.346390,72.518756,72.671854,72.810878,72.936854,73.052366,NaN,NaN
VEN,"Venezuela, RB","Life expectancy at birth, total (years)",SP.DYN.LE00.IN,59.285122,59.862561,60.430317,60.985829,61.529073,62.062073,62.588805,...,73.476244,73.568000,73.671610,73.791659,73.925732,74.074415,74.236195,74.409610,NaN,NaN
VGB,British Virgin Islands,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VIR,Virgin Islands (U.S.),"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,63.730220,64.101561,64.462561,64.828756,65.210122,65.611610,66.032585,...,78.924390,79.073171,79.173171,79.373171,79.473171,79.624390,79.773171,79.873171,NaN,NaN
VNM,Vietnam,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,59.067024,59.744195,60.410537,61.043024,61.607146,61.996780,62.087390,...,74.653098,74.822610,74.990366,75.156805,75.319390,75.477000,75.629122,75.777732,NaN,NaN
VUT,Vanuatu,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,46.487488,47.088098,47.688195,48.287293,48.886829,49.484780,50.083122,...,70.254756,70.555829,70.849951,71.134561,71.408171,71.669244,71.918317,72.157366,NaN,NaN
WLD,World,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,52.474764,52.980853,53.404196,53.935462,54.612963,55.280440,56.020013,...,69.904202,70.208945,70.471632,70.748179,70.983615,71.226337,71.458982,71.663961,NaN,NaN
WSM,Samoa,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,49.969512,50.469512,50.969512,51.469512,51.969512,52.469512,52.969512,...,71.844293,72.130683,72.417000,72.701268,72.980049,73.250390,73.511829,73.764878,NaN,NaN
XKX,Kosovo,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,69.397561,69.648780,69.900000,70.148780,70.497561,70.797561,71.097561,71.346341,NaN,NaN
YEM,"Yemen, Rep.","Life expectancy at birth, total (years)",SP.DYN.LE00.IN,34.363805,34.473244,34.739561,35.186780,35.812878,36.593390,37.482317,...,62.211366,62.485341,62.768732,63.053537,63.327293,63.583512,63.818195,64.031390,NaN,NaN
ZAF,South Africa,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,49.036293,49.429805,49.813293,50.195756,50.581756,50.971829,51.363024,...,52.636024,53.467098,54.390756,55.295659,56.098317,56.736585,57.182122,57.440902,NaN,NaN
ZMB,Zambia,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,45.109805,45.487512,45.853659,46.208732,46.557683,46.911512,47.283268,...,53.905634,55.214171,56.383854,57.422195,58.363317,59.237366,60.047049,60.785683,NaN,NaN
ZWE,Zimbabwe,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,51.542463,51.914951,52.277902,52.629317,52.971659,53.304463,53.627707,...,45.804488,47.624659,49.574659,51.600366,53.643073,55.633000,57.498317,59.161073,NaN,NaN

In [4]:
pop = pd.read_csv("../data/population.csv").set_index("Country Code")
pop

,Country Name,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,Unnamed: 61
Country Code,,,,,,,,,,,,,,,,,,,,,
ABW,Aruba,"Population, total",SP.POP.TOTL,5.421100e+04,5.543800e+04,5.622500e+04,5.669500e+04,5.703200e+04,5.736000e+04,5.771500e+04,...,1.013530e+05,1.014530e+05,1.016690e+05,1.020530e+05,1.025770e+05,1.031870e+05,1.037950e+05,1.043410e+05,1.048220e+05,NaN
AFG,Afghanistan,"Population, total",SP.POP.TOTL,8.996351e+06,9.166764e+06,9.345868e+06,9.533954e+06,9.731361e+06,9.938414e+06,1.015233e+07,...,2.729403e+07,2.800433e+07,2.880317e+07,2.970860e+07,3.069696e+07,3.173169e+07,3.275802e+07,3.373649e+07,3.465603e+07,NaN
AGO,Angola,"Population, total",SP.POP.TOTL,5.643182e+06,5.753024e+06,5.866061e+06,5.980417e+06,6.093321e+06,6.203299e+06,6.309770e+06,...,2.175942e+07,2.254955e+07,2.336913e+07,2.421856e+07,2.509615e+07,2.599834e+07,2.692047e+07,2.785930e+07,2.881346e+07,NaN
ALB,Albania,"Population, total",SP.POP.TOTL,1.608800e+06,1.659800e+06,1.711319e+06,1.762621e+06,1.814135e+06,1.864791e+06,1.914573e+06,...,2.947314e+06,2.927519e+06,2.913021e+06,2.905195e+06,2.900401e+06,2.895092e+06,2.889104e+06,2.880703e+06,2.876101e+06,NaN
AND,Andorra,"Population, total",SP.POP.TOTL,1.341100e+04,1.437500e+04,1.537000e+04,1.641200e+04,1.746900e+04,1.854900e+04,1.964700e+04,...,8.386100e+04,8.446200e+04,8.444900e+04,8.375100e+04,8.243100e+04,8.078800e+04,7.922300e+04,7.801400e+04,7.728100e+04,NaN
ARB,Arab World,"Population, total",SP.POP.TOTL,9.249093e+07,9.504450e+07,9.768229e+07,1.004111e+08,1.032399e+08,1.061750e+08,1.092306e+08,...,3.398255e+08,3.481451e+08,3.565089e+08,3.648959e+08,3.733070e+08,3.817021e+08,3.900430e+08,3.983050e+08,4.064527e+08,NaN
ARE,United Arab Emirates,"Population, total",SP.POP.TOTL,9.263400e+04,1.010780e+05,1.124720e+05,1.255660e+05,1.385290e+05,1.503620e+05,1.604810e+05,...,6.894278e+06,7.666393e+06,8.270684e+06,8.672475e+06,8.900453e+06,9.006263e+06,9.070867e+06,9.154302e+06,9.269612e+06,NaN
ARG,Argentina,"Population, total",SP.POP.TOTL,2.061908e+07,2.095308e+07,2.128768e+07,2.162184e+07,2.195393e+07,2.228339e+07,2.260875e+07,...,4.038239e+07,4.079941e+07,4.122389e+07,4.165688e+07,4.209674e+07,4.253992e+07,4.298152e+07,4.341776e+07,4.384743e+07,NaN
ARM,Armenia,"Population, total",SP.POP.TOTL,1.874120e+06,1.941491e+06,2.009526e+06,2.077575e+06,2.144998e+06,2.211316e+06,2.276031e+06,...,2.908220e+06,2.888584e+06,2.877311e+06,2.875581e+06,2.881922e+06,2.893509e+06,2.906220e+06,2.916950e+06,2.924816e+06,NaN
ASM,American Samoa,"Population, total",SP.POP.TOTL,2.001300e+04,2.048600e+04,2.111700e+04,2.188200e+04,2.269800e+04,2.352000e+04,2.432100e+04,...,5.703000e+04,5.622700e+04,5.563700e+04,5.532000e+04,5.523000e+04,5.530700e+04,5.543700e+04,5.553700e+04,5.559900e+04,NaN
ATG,Antigua and Barbuda,"Population, total",SP.POP.TOTL,5.533900e+04,5.614400e+04,5.714400e+04,5.829400e+04,5.952400e+04,6.078100e+04,6.205900e+04,...,9.247800e+04,9.358100e+04,9.466100e+04,9.571900e+04,9.677700e+04,9.782400e+04,9.887500e+04,9.992300e+04,1.009630e+05,NaN
AUS,Australia,"Population, total",SP.POP.TOTL,1.027648e+07,1.048300e+07,1.074200e+07,1.095000e+07,1.116700e+07,1.138800e+07,1.165100e+07,...,2.124920e+07,2.169170e+07,2.203175e+07,2.234002e+07,2.272825e+07,2.311735e+07,2.346069e+07,2.378934e+07,2.412716e+07,NaN
AUT,Austria,"Population, total",SP.POP.TOTL,7.047539e+06,7.086299e+06,7.129864e+06,7.175811e+06,7.223801e+06,7.270889e+06,7.322066e+06,...,8.321496e+06,8.343323e+06,8.363404e+06,8.391643e+06,8.429991e+06,8.479375e+06,8.541575e+06,8.633169e+06,8.747358e+06,NaN
AZE,Azerbaijan,"Population, total",SP.POP.TOTL,3.895396e+06,4.030320e+06,4.171425e+06,4.315128e+06,4.456689e+06,4.592610e+06,4.721525e+06,...,8.763400e+06,8.947243e+06,9.054332e+06,9.173082e+06,9.295784e+06,9.416801e+06,9.535079e+06,9.649341e+06,9.762274e+06,NaN
BDI,Burundi,"Population, total",SP.POP.TOTL,2.786106e+06,2.839666e+06,2.893669e+06,2.949926e+06,3.010859e+06,3.077876e+06,3.152723e+06,...,8.212264e+06,8.489031e+06,8.766930e+06,9.043508e+06,9.319710e+06,9.600186e+06,9.891790e+06,1.019927e+07,1.052412e+07,NaN
BEL,Belgium,"Population, total",SP.POP.TOTL,9.153489e+06,9.183948e+06,9.220578e+06,9.289770e+06,9.378113e+06,9.463667e+06,9.527807e+06,...,1.070997e+07,1.079649e+07,1.089559e+07,1.104774e+07,1.112825e+07,1.118282e+07,1.120906e+07,1.127420e+07,1.134816e+07,NaN
BEN,Benin,"Population, total",SP.POP.TOTL,2.431622e+06,2.465867e+06,2.502896e+06,2.542859e+06,2.585965e+06,2.632356e+06,2.682159e+06,...,8.696916e+06,8.944706e+06,9.199259e+06,9.460802e+06,9.729160e+06,1.000445e+07,1.028671e+07,1.057595e+07,1.087230e+07,NaN
BFA,Burkina Faso,"Population, total",SP.POP.TOTL,4.829288e+06,4.894580e+06,4.960326e+06,5.027821e+06,5.098890e+06,5.174870e+06,5.256363e+06,...,1.468973e+07,1.514110e+07,1.560522e+07,1.608190e+07,1.657122e+07,1.707272e+07,1.758598e+07,1.811062e+07,1.864643e+07,NaN
BGD,Bangladesh,"Population, total",SP.POP.TOTL,4.819975e+07,4.959280e+07,5.103014e+07,5.253242e+07,5.412910e+07,5.583404e+07,5.767299e+07,...,1.488058e+08,1.504547e+08,1.521491e+08,1.539119e+08,1.557271e+08,1.575713e+08,1.594053e+08,1.612009e+08,1.629516e+08,NaN
BGR,Bulgaria,"Population, total",SP.POP.TOTL,7.867374e+06,7.943118e+06,8.012946e+06,8.078145e+06,8.144340e+06,8.204168e+06,8.258057e+06,...,7.492561e+06,7.444443e+06,7.395599e+06,7.348328e+06,7.305888e+06,7.265115e+06,7.223938e+06,7.177991e+06,7.127822e+06,NaN
BHR,Bahrain,"Population, total",SP.POP.TOTL,1.624270e+05,1.678940e+05,1.731440e+05,1.781400e+05,1.828870e+05,1.874310e+05,1.917800e+05,...,1.114590e+06,1.185029e+06,1.240862e+06,1.278269e+06,1.300217e+06,1.315411e+06,1.336397e+06,1.371855e+06,1.425171e+06,NaN
BHS,"Bahamas, The","Population, total",SP.POP.TOTL,1.095280e+05,1.151080e+05,1.210830e+05,1.273330e+05,1.336980e+05,1.400540e+05,1.463660e+05,...,3.486760e+05,3.548560e+05,3.608320e+05,3.665680e+05,3.720390e+05,3.772400e+05,3.821690e+05,3.868380e+05,3.912320e+05,NaN
BIH,Bosnia and Herzegovina,"Population, total",SP.POP.TOTL,3.225668e+06,3.288602e+06,3.353226e+06,3.417574e+06,3.478995e+06,3.535640e+06,3.586634e+06,...,3.763599e+06,3.746561e+06,3.722084e+06,3.688865e+06,3.648200e+06,3.604999e+06,3.566002e+06,3.535961e+06,3.516816e+06,NaN
BLR,Belarus,"Population, total",SP.POP.TOTL,8.198000e+06,8.271216e+06,8.351928e+06,8.437232e+06,8.524224e+06,8.610000e+06,8.696496e+06,...,9.527985e+06,9.506765e+06,9.490583e+06,9.473172e+06,9.464495e+06,9.465997e+06,9.474511e+06,9.489616e+06,9.507120e+06,NaN
BLZ,Belize,"Population, total",SP.POP.TOTL,9.206400e+04,9.470300e+04,9.738400e+04,1.001640e+05,1.030690e+05,1.061190e+05,1.093470e+05,...,3.061650e+05,3.139290e+05,3.216080e+05,3.291920e+05,3.367010e+05,3.441810e+05,3.516940e+05,3.592880e+05,3.669540e+05,NaN
BMU,Bermuda,"Population, total",SP.POP.TOTL,4.440000e+04,4.550000e+04,4.660000e+04,4.770000e+04,4.890000e+04,5.010000e+04,5.100000e+04,...,6.527300e+04,6.563600e+04,6.512400e+04,6.456400e+04,6.479800e+04,6.500100e+04,6.513900e+04,6.523500e+04,6.533100e+04,NaN
BOL,Bolivia,"Population, total",SP.POP.TOTL,3.693449e+06,3.764813e+06,3.838097e+06,3.913395e+06,3.990857e+06,4.070590e+06,4.152668e+06,...,9.599855e+06,9.758748e+06,9.918242e+06,1.007834e+07,1.023900e+07,1.040026e+07,1.056216e+07,1.072470e+07,1.088788e+07,NaN
BRA,Brazil,"Population, total",SP.POP.TOTL,7.220755e+07,7.435176e+07,7.657325e+07,7.885402e+07,8.116865e+07,8.349802e+07,8.583780e+07,...,1.929790e+08,1.948960e+08,1.967963e+08,1.986867e+08,2.005610e+08,2.024086e+08,2.042131e+08,2.059621e+08,2.076529e+08,NaN
BRB,Barbados,"Population, total",SP.POP.TOTL,2.309390e+05,2.316780e+05,2.325860e+05,2.335870e+05,2.345470e+05,2.353740e+05,2.360440e+05,...,2.773190e+05,2.784700e+05,2.795690e+05,2.806010e+05,2.815850e+05,2.825090e+05,2.833850e+05,2.842170e+05,2.849960e+05,NaN
BRN,Brunei Darussalam,"Population, total",SP.POP.TOTL,8.174500e+04,8.559600e+04,8.951600e+04,9.357600e+04,9.784800e+04,1.024250e+05,1.073160e+05,...,3.792520e+05,3.837720e+05,3.886620e+05,3.940130e+05,3.997480e+05,4.057160e+05,4.117040e+05,4.175420e+05,4.231960e+05,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TLA,Latin America & the Caribbean (IDA & IBRD coun...,"Population, total",SP.POP.TOTL,2.103576e+08,2.162859e+08,2.223965e+08,2.286630e+08,2.350485e+08,2.415251e+08,2.480822e+08,...,5.659562e+08,5.731253e+08,5.802468e+08,5.873151e+08,5.943307e+08,6.012772e+08,6.081360e+08,6.148920e+08,6.215349e+08,NaN
TLS,Timor-Leste,"Population, total",SP.POP.TOTL,4.999500e+05,5.088450e+05,5.181070e+05,5.277490e+05,5.377860e+05,5.482180e+05,5.586760e+05,...,1.078110e+06,1.092021e+06,1.109591e+06,1.131523e+06,1.156760e+06,1.184366e+06,1.212814e+06,1.240977e+06,1.268671e+06,NaN
TMN,Middle East & North Africa (IDA & IBRD countries),"Population, total",SP.POP.TOTL,9.783777e+07,1.004585e+08,1.031472e+08,1.059144e+08,1.087749e+08,1.117382e+08,1.148161e+08,...,3.199345e+08,3.257867e+08,3.317705e+08,3.378950e+08,3.441488e+08,3.504715e+08,3.567833e+08,3.630272e+08,3.691675e+08,NaN
TON,Tonga,"Population, total",SP.POP.TOTL,6.160100e+04,6.374500e+04,6.625900e+04,6.900500e+04,7.175700e+04,7.436200e+04,7.677900e+04,...,1.030050e+05,1.036040e+05,1.041370e+05,1.045770e+05,1.049510e+05,1.053280e+05,1.057820e+05,1.063640e+05,1.071220e+05,NaN
TSA,South Asia (IDA & IBRD),"Population, total",SP.POP.TOTL,5.718572e+08,5.839504e+08,5.965048e+08,6.093763e+08,6.228756e+08,6.367550e+08,6.510947e+08,...,1.584247e+09,1.607562e+09,1.630730e+09,1.653756e+09,1.676614e+09,1.699306e+09,1.721841e+09,1.744191e+09,1.766383e+09,NaN
TSS,Sub-Saharan Africa (IDA & IBRD countries),"Population, total",SP.POP.TOTL,2.285255e+08,2.339380e+08,2.395679e+08,2.454139e+08,2.514716e+08,2.577403e+08,2.642250e+08,...,8.301110e+08,8.532387e+08,8.770231e+08,9.014558e+08,9.265482e+08,9.522786e+08,9.786251e+08,1.005571e+09,1.033106e+09,NaN
TTO,Trinidad and Tobago,"Population, total",SP.POP.TOTL,8.484790e+05,8.653600e+05,8.800230e+05,8.925690e+05,9.032750e+05,9.124170e+05,9.199030e+05,...,1.315372e+06,1.321618e+06,1.328100e+06,1.334788e+06,1.341588e+06,1.348248e+06,1.354493e+06,1.360092e+06,1.364962e+06,NaN
TUN,Tunisia,"Population, total",SP.POP.TOTL,4.176266e+06,4.235937e+06,4.303131e+06,4.377637e+06,4.458611e+06,4.545339e+06,4.638275e+06,...,1.040734e+07,1.052183e+07,1.063993e+07,1.076147e+07,1.088667e+07,1.101456e+07,1.114391e+07,1.127366e+07,1.140325e+07,NaN
TUR,Turkey,"Population, total",SP.POP.TOTL,2.747233e+07,2.814689e+07,2.883280e+07,2.953134e+07,3.024423e+07,3.097296e+07,3.171748e+07,...,7.044003e+07,7.133918e+07,7.232691e+07,7.340946e+07,7.456987e+07,7.578733e+07,7.703063e+07,7.827147e+07,7.951243e+07,NaN
TUV,Tuvalu,"Population, total",SP.POP.TOTL,6.104000e+03,6.246000e+03,6.389000e+03,6.538000e+03,6.684000e+03,6.815000e+03,6.938000e+03,...,1.034000e+04,1.044100e+04,1.053100e+04,1.062800e+04,1.072500e+04,1.081900e+04,1.090800e+04,1.100100e+04,1.109700e+04,NaN
TZA,Tanzania,"Population, total",SP.POP.TOTL,1.007451e+07,1.037340e+07,1.068391e+07,1.100590e+07,1.133910e+07,1.168353e+07,1.203890e+07,...,4.327014e+07,4.466423e+07,4.609859e+07,4.757090e+07,4.908300e+07,5.063660e+07,5.223487e+07,5.387996e+07,5.557220e+07,NaN
UGA,Uganda,"Population, total",SP.POP.TOTL,6.788214e+06,7.006633e+06,7.240174e+06,7.487429e+06,7.746198e+06,8.014401e+06,8.292776e+06,...,3.166390e+07,3.277190e+07,3.391513e+07,3.509365e+07,3.630680e+07,3.755373e+07,3.883334e+07,4.014487e+07,4.148796e+07,NaN
UKR,Ukraine,"Population, total",SP.POP.TOTL,4.266215e+07,4.320364e+07,4.374947e+07,4.428590e+07,4.479433e+07,4.526194e+07,4.568231e+07,...,4.625820e+07,4.605330e+07,4.587070e+07,4.570610e+07,4.559330e+07,4.548960e+07,4.527195e+07,4.515403e+07,4.500464e+07,NaN
UMC,Upper middle income,"Population, total",SP.POP.TOTL,1.169383e+09,1.173938e+09,1.190950e+09,1.219341e+09,1.247382e+09,1.276359e+09,1.308237e+09,...,2.428375e+09,2.446466e+09,2.464535e+09,2.482889e+09,2.501990e+09,2.521455e+09,2.541065e+09,2.560412e+09,2.579910e+09,NaN
URY,Uruguay,"Population, total",SP.POP.TOTL,2.538651e+06,2.571690e+06,2.603887e+06,2.635129e+06,2.665390e+06,2.694537e+06,2.722877e+06,...,3.350824e+06,3.362755e+06,3.374415e+06,3.385624e+06,3.396777e+06,3.408005e+06,3.419546e+06,3.431552e+06,3.444006e+06,NaN
USA,United States,"Population, total",SP.POP.TOTL,1.806710e+08,1.836910e+08,1.865380e+08,1.892420e+08,1.918890e+08,1.943030e+08,1.965600e+08,...,3.040940e+08,3.067715e+08,3.093482e+08,3.116634e+08,3.139984e+08,3.162049e+08,3.185635e+08,3.208966e+08,3.231275e+08,NaN
UZB,Uzbekistan,"Population, total",SP.POP.TOTL,8.549493e+06,8.837349e+06,9.138097e+06,9.454250e+06,9.788986e+06,1.014374e+07,1.052088e+07,...,2.730280e+07,2.776740e+07,2.856240e+07,2.933940e+07,2.977450e+07,3.024320e+07,3.075770e+07,3.129890e+07,3.184820e+07,NaN
VCT,St. Vincent and the Grenadines,"Population, total",SP.POP.TOTL,8.094900e+04,8.214200e+04,8.320600e+04,8.416700e+04,8.506900e+04,8.597000e+04,8.685700e+04,...,1.091650e+05,1.092530e+05,1.093150e+05,1.093410e+05,1.093280e+05,1.093200e+05,1.093570e+05,1.094550e+05,1.096430e+05,NaN
VEN,"Venezuela, RB","Population, total",SP.POP.TOTL,8.146847e+06,8.461685e+06,8.790589e+06,9.130349e+06,9.476252e+06,9.824692e+06,1.017514e+07,...,2.814170e+07,2.858732e+07,2.902803e+07,2.946329e+07,2.989308e+07,3.031785e+07,3.073838e+07,3.115513e+07,3.156818e+07,NaN
VGB,British Virgin Islands,"Population, total",SP.POP.TOTL,8.033000e+03,8.155000e+03,8.298000e+03,8.452000e+03,8.627000e+03,8.814000e+03,9.007000e+03,...,2.560400e+04,2.644700e+04,2.722400e+04,2.790100e+04,2.850900e+04,2.905600e+04,2.958800e+04,3.011300e+04,3.066100e+04,NaN
VIR,Virgin Islands (U.S.),"Population, total",SP.POP.TOTL,3.200000e+04,3.410000e+04,3.630000e+04,3.870000e+04,4.130000e+04,4.400000e+04,4.730000e+04,...,1.070910e+05,1.067070e+05,1.062670e+05,1.057840e+05,1.052750e+05,1.047370e+05,1.041700e+05,1.035740e+05,1.029510e+05,NaN
VNM,Vietnam,"Population, total",SP.POP.TOTL,3.474300e+07,3.542800e+07,3.612300e+07,3.683600e+07,3.757400e+07,3.834100e+07,3.914200e+07,...,8.511870e+07,8.602500e+07,8.693250e+07,8.786030e+07,8.880920e+07,8.975950e+07,9.072890e+07,9.171330e+07,9.270110e+07,NaN
VUT,Vanuatu,"Population, total",SP.POP.TOTL,6.369900e+04,6.571300e+04,6.780800e+04,6.996400e+04,7.213100e+04,7.428900e+04,7.641300e+04,...,2.253400e+05,2.307850e+05,2.362950e+05,2.418710e+05,2.474850e+05,2.531420e+05,2.588500e+05,2.646030e+05,2.704020e+05,NaN
WLD,World,"Population, total",SP.POP.TOTL,3.034193e+09,3.075115e+09,3.127961e+09,3.192794e+09,3.258201e+09,3.324952e+09,3.394865e+09,...,6.763746e+09,6.847215e+09,6.930657e+09,7.012844e+09,7.097401e+09,7.182860e+09,7.268986e+09,7.355220e+09,7.442136e+09,NaN
WSM,Samoa,"Population, total",SP.POP.TOTL,1.086460e+05,1.121190e+05,1.157880e+05,1.195610e+05,1.233540e+05,1.270680e+05,1.306880e+05,...,1.835260e+05,1.848260e+05,1.862050e+05,1.876650e+05,1.891940e+05,1.907570e+05,1.922900e+05,1.937590e+05,1.951250e+05,NaN
XKX,Kosovo,"Population, total",SP.POP.TOTL,9.470000e+05,9.660000e+05,9.940000e+05,1.022000e+06,1.050000e+06,1.078000e+06,1.106000e+06,...,1.747383e+06,1.761474e+06,1.775680e+06,1.791000e+06,1.805200e+06,1.824100e+06,1.821800e+06,1.801800e+06,1.816200e+06,NaN
YEM,"Yemen, Rep.","Population, total",SP.POP.TOTL,5.172135e+06,5.260501e+06,5.351799e+06,5.446063e+06,5.543339e+06,5.643643e+06,5.748588e+06,...,2.235639e+07,2.297493e+07,2.360678e+07,2.425221e+07,2.490997e+07,2.557632e+07,2.624633e+07,2.691621e+07,2.758421e+07,NaN
ZAF,South Africa,"Population, total",SP.POP.TOTL,1.739637e+07,1.785004e+07,1.832234e+07,1.880994e+07,1.930817e+07,1.981395e+07,2.032523e+07,...,4.955757e+07,5.025581e+07,5.097943e+07,5.172935e+07,5.250652e+07,5.331196e+07,5.414673e+07,5.501198e+07,5.590886e+07,NaN
ZMB,Zambia,"Population, total",SP.POP.TOTL,3.044846e+06,3.140264e+06,3.240587e+06,3.345145e+06,3.452942e+06,3.563407e+06,3.676189e+06,...,1.308252e+07,1.345642e+07,1.385003e+07,1.426476e+07,1.469994e+07,1.515321e+07,1.562097e+07,1.610059e+07,1.659139e+07,NaN
ZWE,Zimbabwe,"Population, total",SP.POP.TOTL,3.747369e+06,3.870756e+06,3.999419e+06,4.132756e+06,4.269863e+06,4.410212e+06,4.553433e+06,...,1.355847e+07,1.381060e+07,1.408632e+07,1.438665e+07,1.471083e+07,1.505451e+07,1.541168e+07,1.577745e+07,1.615036e+07,NaN

In [5]:
regions = pd.read_csv("../data/regions.csv").set_index("CountryCode")
regions.rename(columns={"TableName": "CountryName"}, inplace=True)
regions

,Region,IncomeGroup,SpecialNotes,CountryName,Unnamed: 5
CountryCode,,,,,
ABW,Latin America & Caribbean,High income,SNA data for 2000-2011 are updated from offici...,Aruba,NaN
AFG,South Asia,Low income,Fiscal year end: March 20; reporting period fo...,Afghanistan,NaN
AGO,Sub-Saharan Africa,Lower middle income,NaN,Angola,NaN
ALB,Europe & Central Asia,Upper middle income,NaN,Albania,NaN
AND,Europe & Central Asia,High income,WB-3 code changed from ADO to AND to align wit...,Andorra,NaN
ARB,NaN,NaN,Arab World aggregate. Arab World is composed o...,Arab World,NaN
ARE,Middle East & North Africa,High income,NaN,United Arab Emirates,NaN
ARG,Latin America & Caribbean,Upper middle income,National Institute of Statistics and Census re...,Argentina,NaN
ARM,Europe & Central Asia,Lower middle income,NaN,Armenia,NaN
ASM,East Asia & Pacific,Upper middle income,NaN,American Samoa,NaN
ATG,Latin America & Caribbean,High income,NaN,Antigua and Barbuda,NaN
AUS,East Asia & Pacific,High income,Fiscal year end: June 30; reporting period for...,Australia,NaN
AUT,Europe & Central Asia,High income,A simple multiplier is used to convert the nat...,Austria,NaN
AZE,Europe & Central Asia,Upper middle income,NaN,Azerbaijan,NaN
BDI,Sub-Saharan Africa,Low income,NaN,Burundi,NaN
BEL,Europe & Central Asia,High income,A simple multiplier is used to convert the nat...,Belgium,NaN
BEN,Sub-Saharan Africa,Low income,NaN,Benin,NaN
BFA,Sub-Saharan Africa,Low income,NaN,Burkina Faso,NaN
BGD,South Asia,Lower middle income,Fiscal year end: June 30; reporting period for...,Bangladesh,NaN
BGR,Europe & Central Asia,Upper middle income,The new reference year for chain linked series...,Bulgaria,NaN
BHR,Middle East & North Africa,High income,NaN,Bahrain,NaN
BHS,Latin America & Caribbean,High income,NaN,"Bahamas, The",NaN
BIH,Europe & Central Asia,Upper middle income,NaN,Bosnia and Herzegovina,NaN
BLR,Europe & Central Asia,Upper middle income,In July 2016 a new Belarusian ruble was introd...,Belarus,NaN
BLZ,Latin America & Caribbean,Upper middle income,NaN,Belize,NaN
BMU,North America,High income,NaN,Bermuda,NaN
BOL,Latin America & Caribbean,Lower middle income,NaN,Bolivia,NaN
BRA,Latin America & Caribbean,Upper middle income,NaN,Brazil,NaN
BRB,Latin America & Caribbean,High income,NaN,Barbados,NaN
BRN,East Asia & Pacific,High income,National accounts revision is based on data fr...,Brunei Darussalam,NaN
...,...,...,...,...,...
TLA,NaN,NaN,Latin America & the Caribbean (IDA & IBRD coun...,Latin America & Caribbean (IDA & IBRD),NaN
TLS,East Asia & Pacific,Lower middle income,WB-3 code changed from TMP to TLS to align wit...,Timor-Leste,NaN
TMN,NaN,NaN,Middle East & North Africa (IDA & IBRD countri...,Middle East & North Africa (IDA & IBRD),NaN
TON,East Asia & Pacific,Upper middle income,NaN,Tonga,NaN
TSA,NaN,NaN,South Asia (IDA & IBRD countries) aggregate.,South Asia (IDA & IBRD),NaN
TSS,NaN,NaN,Sub-Saharan Africa (IDA & IBRD countries) aggr...,Sub-Saharan Africa (IDA & IBRD),NaN
TTO,Latin America & Caribbean,High income,NaN,Trinidad and Tobago,NaN
TUN,Middle East & North Africa,Lower middle income,NaN,Tunisia,NaN
TUR,Europe & Central Asia,Upper middle income,NaN,Turkey,NaN
TUV,East Asia & Pacific,Upper middle income,Value added is measured at producer prices up ...,Tuvalu,NaN
TZA,Sub-Saharan Africa,Low income,Tanzania reports using a blend of SNA 1993 and...,Tanzania,NaN
UGA,Sub-Saharan Africa,Low income,Fiscal year end: June 30; reporting period for...,Uganda,NaN
UKR,Europe & Central Asia,Lower middle income,The new base year is 2010.,Ukraine,NaN
UMC,NaN,NaN,Upper middle income group aggregate. Upper-mid...,Upper middle income,NaN
URY,Latin America & Caribbean,High income,NaN,Uruguay,NaN
USA,North America,High income,Fiscal year end: September 30; reporting perio...,United States,NaN
UZB,Europe & Central Asia,Lower middle income,NaN,Uzbekistan,NaN
VCT,Latin America & Caribbean,Upper middle income,NaN,St. Vincent and the Grenadines,NaN
VEN,Latin America & Caribbean,Upper middle income,NaN,"Venezuela, RB",NaN
VGB,Latin America & Caribbean,High income,NaN,British Virgin Islands,NaN
VIR,Latin America & Caribbean,High income,NaN,Virgin Islands (U.S.),NaN
VNM,East Asia & Pacific,Lower middle income,NaN,Vietnam,NaN
VUT,East Asia & Pacific,Lower middle income,"Based on official government statistics, value...",Vanuatu,NaN
WLD,NaN,NaN,World aggregate.,World,NaN
WSM,East Asia & Pacific,Upper middle income,Fiscal year ends on June 30; reporting period ...,Samoa,NaN
XKX,Europe & Central Asia,Lower middle income,WB-3 code changed from KSV to XKX to align wit...,Kosovo,NaN
YEM,Middle East & North Africa,Lower middle income,Based on official government statistics and In...,"Yemen, Rep.",NaN
ZAF,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...,South Africa,NaN
ZMB,Sub-Saharan Africa,Lower middle income,The base year is 2010. National accounts data ...,Zambia,NaN
ZWE,Sub-Saharan Africa,Low income,Fiscal year end: June 30; reporting period for...,Zimbabwe,NaN

In [6]:
def pivot(df, cn):
    le = pd.DataFrame(columns=['Key', 'CountryCode', 'Year', cn])
    countries = df.index.values
    for c in countries:
        for y in range(1960, 2016):
            #print (c, y)
            le.loc[len(le)] =[(c + '.' + str(y)), c, y, df.loc[c][str(y)]]
    le = le.set_index('Key')
    return le

In [7]:
fr = pivot(fert, 'FertRate')
#le.set_index("Key")
fr

         CountryCode  Year  FertRate
Key
ABW.1960         ABW  1960     4.820
ABW.1961         ABW  1961     4.655
ABW.1962         ABW  1962     4.471
ABW.1963         ABW  1963     4.271
ABW.1964         ABW  1964     4.059
ABW.1965         ABW  1965     3.842
ABW.1966         ABW  1966     3.625
ABW.1967         ABW  1967     3.417
ABW.1968         ABW  1968     3.226
ABW.1969         ABW  1969     3.054
ABW.1970         ABW  1970     2.908
ABW.1971         ABW  1971     2.788
ABW.1972         ABW  1972     2.691
ABW.1973         ABW  1973     2.613
ABW.1974         ABW  1974     2.552
ABW.1975         ABW  1975     2.506
ABW.1976         ABW  1976     2.472
ABW.1977         ABW  1977     2.446
ABW.1978         ABW  1978     2.425
ABW.1979         ABW  1979     2.408
ABW.1980         ABW  1980     2.392
ABW.1981         ABW  1981     2.377
ABW.1982         ABW  1982     2.364
ABW.1983         ABW  1983     2.353
ABW.1984         ABW  1984     2.342
ABW.1985         ABW  1985     2.332
ABW.1986         ABW  1986     2.320
ABW.1987         ABW  1987     2.307
ABW.1988         ABW  1988     2.291
ABW.1989         ABW  1989     2.272
...              ...   ...       ...
ZWE.1986         ZWE  1986     6.004
ZWE.1987         ZWE  1987     5.784
ZWE.1988         ZWE  1988     5.569
ZWE.1989         ZWE  1989     5.365
ZWE.1990         ZWE  1990     5.176
ZWE.1991         ZWE  1991     5.001
ZWE.1992         ZWE  1992     4.840
ZWE.1993         ZWE  1993     4.690
ZWE.1994         ZWE  1994     4.553
ZWE.1995         ZWE  1995     4.431
ZWE.1996         ZWE  1996     4.326
ZWE.1997         ZWE  1997     4.237
ZWE.1998         ZWE  1998     4.165
ZWE.1999         ZWE  1999     4.108
ZWE.2000         ZWE  2000     4.065
ZWE.2001         ZWE  2001     4.036
ZWE.2002         ZWE  2002     4.018
ZWE.2003         ZWE  2003     4.008
ZWE.2004         ZWE  2004     4.005
ZWE.2005         ZWE  2005     4.006
ZWE.2006         ZWE  2006     4.012
ZWE.2007         ZWE  2007     4.022
ZWE.2008         ZWE  2008     4.034
ZWE.2009         ZWE  2009     4.044
ZWE.2010         ZWE  2010     4.048
ZWE.2011         ZWE  2011     4.039
ZWE.2012         ZWE  2012     4.016
ZWE.2013         ZWE  2013     3.977
ZWE.2014         ZWE  2014     3.923
ZWE.2015         ZWE  2015     3.856

[14784 rows x 3 columns]

In [8]:
le = pivot(lfe, "LifeExp")
le

         CountryCode  Year    LifeExp
Key
ABW.1960         ABW  1960  65.569366
ABW.1961         ABW  1961  65.988024
ABW.1962         ABW  1962  66.365537
ABW.1963         ABW  1963  66.713976
ABW.1964         ABW  1964  67.044293
ABW.1965         ABW  1965  67.369756
ABW.1966         ABW  1966  67.699000
ABW.1967         ABW  1967  68.034683
ABW.1968         ABW  1968  68.377146
ABW.1969         ABW  1969  68.728415
ABW.1970         ABW  1970  69.086146
ABW.1971         ABW  1971  69.446098
ABW.1972         ABW  1972  69.798659
ABW.1973         ABW  1973  70.139659
ABW.1974         ABW  1974  70.465293
ABW.1975         ABW  1975  70.777805
ABW.1976         ABW  1976  71.080829
ABW.1977         ABW  1977  71.377707
ABW.1978         ABW  1978  71.669780
ABW.1979         ABW  1979  71.952854
ABW.1980         ABW  1980  72.220146
ABW.1981         ABW  1981  72.462341
ABW.1982         ABW  1982  72.673195
ABW.1983         ABW  1983  72.849024
ABW.1984         ABW  1984  72.989756
ABW.1985         ABW  1985  73.097976
ABW.1986         ABW  1986  73.179366
ABW.1987         ABW  1987  73.242707
ABW.1988         ABW  1988  73.296244
ABW.1989         ABW  1989  73.344488
...              ...   ...        ...
ZWE.1986         ZWE  1986  61.925317
ZWE.1987         ZWE  1987  61.753805
ZWE.1988         ZWE  1988  61.322634
ZWE.1989         ZWE  1989  60.612878
ZWE.1990         ZWE  1990  59.583073
ZWE.1991         ZWE  1991  58.197171
ZWE.1992         ZWE  1992  56.491976
ZWE.1993         ZWE  1993  54.538707
ZWE.1994         ZWE  1994  52.422122
ZWE.1995         ZWE  1995  50.239000
ZWE.1996         ZWE  1996  48.087634
ZWE.1997         ZWE  1997  46.065902
ZWE.1998         ZWE  1998  44.272585
ZWE.1999         ZWE  1999  42.791488
ZWE.2000         ZWE  2000  41.689439
ZWE.2001         ZWE  2001  40.996805
ZWE.2002         ZWE  2002  40.679146
ZWE.2003         ZWE  2003  40.702488
ZWE.2004         ZWE  2004  41.059341
ZWE.2005         ZWE  2005  41.759610
ZWE.2006         ZWE  2006  42.810707
ZWE.2007         ZWE  2007  44.177756
ZWE.2008         ZWE  2008  45.804488
ZWE.2009         ZWE  2009  47.624659
ZWE.2010         ZWE  2010  49.574659
ZWE.2011         ZWE  2011  51.600366
ZWE.2012         ZWE  2012  53.643073
ZWE.2013         ZWE  2013  55.633000
ZWE.2014         ZWE  2014  57.498317
ZWE.2015         ZWE  2015  59.161073

[14784 rows x 3 columns]

In [9]:
p = pivot(pop, "Population")
p

         CountryCode  Year  Population
Key
ABW.1960         ABW  1960     54211.0
ABW.1961         ABW  1961     55438.0
ABW.1962         ABW  1962     56225.0
ABW.1963         ABW  1963     56695.0
ABW.1964         ABW  1964     57032.0
ABW.1965         ABW  1965     57360.0
ABW.1966         ABW  1966     57715.0
ABW.1967         ABW  1967     58055.0
ABW.1968         ABW  1968     58386.0
ABW.1969         ABW  1969     58726.0
ABW.1970         ABW  1970     59063.0
ABW.1971         ABW  1971     59440.0
ABW.1972         ABW  1972     59840.0
ABW.1973         ABW  1973     60243.0
ABW.1974         ABW  1974     60528.0
ABW.1975         ABW  1975     60657.0
ABW.1976         ABW  1976     60586.0
ABW.1977         ABW  1977     60366.0
ABW.1978         ABW  1978     60103.0
ABW.1979         ABW  1979     59980.0
ABW.1980         ABW  1980     60096.0
ABW.1981         ABW  1981     60567.0
ABW.1982         ABW  1982     61345.0
ABW.1983         ABW  1983     62201.0
ABW.1984         ABW  1984     62836.0
ABW.1985         ABW  1985     63026.0
ABW.1986         ABW  1986     62644.0
ABW.1987         ABW  1987     61833.0
ABW.1988         ABW  1988     61079.0
ABW.1989         ABW  1989     61032.0
...              ...   ...         ...
ZWE.1986         ZWE  1986   8976205.0
ZWE.1987         ZWE  1987   9293283.0
ZWE.1988         ZWE  1988   9604302.0
ZWE.1989         ZWE  1989   9902540.0
ZWE.1990         ZWE  1990  10183113.0
ZWE.1991         ZWE  1991  10443043.0
ZWE.1992         ZWE  1992  10682868.0
ZWE.1993         ZWE  1993  10905756.0
ZWE.1994         ZWE  1994  11116948.0
ZWE.1995         ZWE  1995  11320346.0
ZWE.1996         ZWE  1996  11518262.0
ZWE.1997         ZWE  1997  11709997.0
ZWE.1998         ZWE  1998  11893272.0
ZWE.1999         ZWE  1999  12064537.0
ZWE.2000         ZWE  2000  12222251.0
ZWE.2001         ZWE  2001  12366165.0
ZWE.2002         ZWE  2002  12500525.0
ZWE.2003         ZWE  2003  12633897.0
ZWE.2004         ZWE  2004  12777511.0
ZWE.2005         ZWE  2005  12940032.0
ZWE.2006         ZWE  2006  13124267.0
ZWE.2007         ZWE  2007  13329909.0
ZWE.2008         ZWE  2008  13558469.0
ZWE.2009         ZWE  2009  13810599.0
ZWE.2010         ZWE  2010  14086317.0
ZWE.2011         ZWE  2011  14386649.0
ZWE.2012         ZWE  2012  14710826.0
ZWE.2013         ZWE  2013  15054506.0
ZWE.2014         ZWE  2014  15411675.0
ZWE.2015         ZWE  2015  15777451.0

[14784 rows x 3 columns]

In [30]:
result = fr.copy().dropna()
result["LifeExp"] = le["LifeExp"]
result["Population"] = p["Population"]
result = result.reset_index().set_index("CountryCode")

In [31]:
result = result.join(regions[["Region", "CountryName"]])
result = result.reset_index()[["CountryCode", "Year", "CountryName", "LifeExp", "FertRate", "Population", "Region"]]
result

,CountryCode,Year,CountryName,LifeExp,FertRate,Population,Region
0,ABW,1960,Aruba,65.569366,4.820,54211.0,Latin America & Caribbean
1,ABW,1961,Aruba,65.988024,4.655,55438.0,Latin America & Caribbean
2,ABW,1962,Aruba,66.365537,4.471,56225.0,Latin America & Caribbean
3,ABW,1963,Aruba,66.713976,4.271,56695.0,Latin America & Caribbean
4,ABW,1964,Aruba,67.044293,4.059,57032.0,Latin America & Caribbean
5,ABW,1965,Aruba,67.369756,3.842,57360.0,Latin America & Caribbean
6,ABW,1966,Aruba,67.699000,3.625,57715.0,Latin America & Caribbean
7,ABW,1967,Aruba,68.034683,3.417,58055.0,Latin America & Caribbean
8,ABW,1968,Aruba,68.377146,3.226,58386.0,Latin America & Caribbean
9,ABW,1969,Aruba,68.728415,3.054,58726.0,Latin America & Caribbean
10,ABW,1970,Aruba,69.086146,2.908,59063.0,Latin America & Caribbean
11,ABW,1971,Aruba,69.446098,2.788,59440.0,Latin America & Caribbean
12,ABW,1972,Aruba,69.798659,2.691,59840.0,Latin America & Caribbean
13,ABW,1973,Aruba,70.139659,2.613,60243.0,Latin America & Caribbean
14,ABW,1974,Aruba,70.465293,2.552,60528.0,Latin America & Caribbean
15,ABW,1975,Aruba,70.777805,2.506,60657.0,Latin America & Caribbean
16,ABW,1976,Aruba,71.080829,2.472,60586.0,Latin America & Caribbean
17,ABW,1977,Aruba,71.377707,2.446,60366.0,Latin America & Caribbean
18,ABW,1978,Aruba,71.669780,2.425,60103.0,Latin America & Caribbean
19,ABW,1979,Aruba,71.952854,2.408,59980.0,Latin America & Caribbean
20,ABW,1980,Aruba,72.220146,2.392,60096.0,Latin America & Caribbean
21,ABW,1981,Aruba,72.462341,2.377,60567.0,Latin America & Caribbean
22,ABW,1982,Aruba,72.673195,2.364,61345.0,Latin America & Caribbean
23,ABW,1983,Aruba,72.849024,2.353,62201.0,Latin America & Caribbean
24,ABW,1984,Aruba,72.989756,2.342,62836.0,Latin America & Caribbean
25,ABW,1985,Aruba,73.097976,2.332,63026.0,Latin America & Caribbean
26,ABW,1986,Aruba,73.179366,2.320,62644.0,Latin America & Caribbean
27,ABW,1987,Aruba,73.242707,2.307,61833.0,Latin America & Caribbean
28,ABW,1988,Aruba,73.296244,2.291,61079.0,Latin America & Caribbean
29,ABW,1989,Aruba,73.344488,2.272,61032.0,Latin America & Caribbean
...,...,...,...,...,...,...,...
13493,ZWE,1986,Zimbabwe,61.925317,6.004,8976205.0,Sub-Saharan Africa
13494,ZWE,1987,Zimbabwe,61.753805,5.784,9293283.0,Sub-Saharan Africa
13495,ZWE,1988,Zimbabwe,61.322634,5.569,9604302.0,Sub-Saharan Africa
13496,ZWE,1989,Zimbabwe,60.612878,5.365,9902540.0,Sub-Saharan Africa
13497,ZWE,1990,Zimbabwe,59.583073,5.176,10183113.0,Sub-Saharan Africa
13498,ZWE,1991,Zimbabwe,58.197171,5.001,10443043.0,Sub-Saharan Africa
13499,ZWE,1992,Zimbabwe,56.491976,4.840,10682868.0,Sub-Saharan Africa
13500,ZWE,1993,Zimbabwe,54.538707,4.690,10905756.0,Sub-Saharan Africa
13501,ZWE,1994,Zimbabwe,52.422122,4.553,11116948.0,Sub-Saharan Africa
13502,ZWE,1995,Zimbabwe,50.239000,4.431,11320346.0,Sub-Saharan Africa
13503,ZWE,1996,Zimbabwe,48.087634,4.326,11518262.0,Sub-Saharan Africa
13504,ZWE,1997,Zimbabwe,46.065902,4.237,11709997.0,Sub-Saharan Africa
13505,ZWE,1998,Zimbabwe,44.272585,4.165,11893272.0,Sub-Saharan Africa
13506,ZWE,1999,Zimbabwe,42.791488,4.108,12064537.0,Sub-Saharan Africa
13507,ZWE,2000,Zimbabwe,41.689439,4.065,12222251.0,Sub-Saharan Africa
13508,ZWE,2001,Zimbabwe,40.996805,4.036,12366165.0,Sub-Saharan Africa
13509,ZWE,2002,Zimbabwe,40.679146,4.018,12500525.0,Sub-Saharan Africa
13510,ZWE,2003,Zimbabwe,40.702488,4.008,12633897.0,Sub-Saharan Africa
13511,ZWE,2004,Zimbabwe,41.059341,4.005,12777511.0,Sub-Saharan Africa
13512,ZWE,2005,Zimbabwe,41.759610,4.006,12940032.0,Sub-Saharan Africa
13513,ZWE,2006,Zimbabwe,42.810707,4.012,13124267.0,Sub-Saharan Africa
13514,ZWE,2007,Zimbabwe,44.177756,4.022,13329909.0,Sub-Saharan Africa
13515,ZWE,2008,Zimbabwe,45.804488,4.034,13558469.0,Sub-Saharan Africa
13516,ZWE,2009,Zimbabwe,47.624659,4.044,13810599.0,Sub-Saharan Africa
13517,ZWE,2010,Zimbabwe,49.574659,4.048,14086317.0,Sub-Saharan Africa
13518,ZWE,2011,Zimbabwe,51.600366,4.039,14386649.0,Sub-Saharan Africa
13519,ZWE,2012,Zimbabwe,53.643073,4.016,14710826.0,Sub-Saharan Africa
13520,ZWE,2013,Zimbabwe,55.633000,3.977,15054506.0,Sub-Saharan Africa
13521,ZWE,2014,Zimbabwe,57.498317,3.923,15411675.0,Sub-Saharan Africa
13522,ZWE,2015,Zimbabwe,59.161073,3.856,15777451.0,Sub-Saharan Africa

In [32]:
result.to_csv("../data/chart_data.csv", index=False)

In [33]:
result[result.Year==2015].to_csv("../data/year2015.csv", index=False)